numero1 = input("anna numero jokin numero:")
numero2 = input("anna toinen numero:")
numero3 = input("anna komlas numero:")
numero4 = float(numero1)
numero5 = float(numero2)
numero6 = float(numero3)
print(f"numerojen summa on:{numero4+numero5+numero6:.2f}")
print(f"numerojen tulo on:{numero4*numero5*numero6:.2f}")
keskiarvo = float(numero4+numero5+numero6)
print(f"numerojen keskiarvo on:{keskiarvo/3:.2f}")
